# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b221b8a08204b4e0766a69449648f00"
name = "remix-app"
handle = "remix-app-85"
application_url = "https://geometry-champion-raid-plain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rrfv.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://geometry-champion-raid-plain.trycloudflare.com/auth/callback",
  "https://geometry-champion-raid-plain.trycloudflare.com/auth/shopify/callback",
  "https://geometry-champion-raid-plain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
